SYSTEM_PROMPT = """당신은 한국 PC 견적 전문가입니다. 호환성 규칙을 반드시 지키세요.
- AMD 7000/9000번대 → AM5 보드 + DDR5 필수
- AMD 5000번대 → AM4 보드 + DDR4 필수
- Intel 12~14세대 → LGA1700 보드 필수
- SSD는 기본값 2개"""

SEARCH_KEYWORDS_PROMPT = """예산 {budget}원, 용도 "{user_request}"에 맞는 부품 검색 키워드를 아래 형식으로만 출력하라.
키워드는 제품명/스펙 1~2단어로 간략하게.

[CPU_LOW] ...
[CPU_MID] ...
[CPU_HIGH] ...
[GPU_LOW] ...
[GPU_MID] ...
[GPU_HIGH] ...
[MAINBORD_LOW] ...
[MAINBORD_MID] ...
[MAINBORD_HIGH] ...
[RAM_LOW] ...
[RAM_MID] ...
[RAM_HIGH] ...
[POWER_LOW] ...
[POWER_MID] ...
[POWER_HIGH] ...
[CASE_LOW] ...
[CASE_MID] ...
[CASE_HIGH] ...
[SSD_LOW] ...
[SSD_MID] ...
[SSD_HIGH] ...
[COOLER_LOW] ...
[COOLER_MID] ...
[COOLER_HIGH] ..."""

GENERATE_QUOTE_PROMPT = """아래 부품 후보로 컨셉이 다른 견적 5개를 만들어라.
소켓/DDR 호환성을 반드시 지켜라.

예산: {budget}원
용도: {user_request}

[부품 후보]
{filtered_parts}

출력 형식 (5개 반복):
조합 N (컨셉명)
▪️ CPU: 제품명
▪️ 메인보드: 제품명
▪️ RAM: 제품명
▪️ GPU: 제품명
▪️ SSD: 제품명
▪️ 파워: 제품명
▪️ 케이스: 제품명
▪️ 쿨러: 제품명
합계: N원
설명: 한 줄 요약"""
